	
#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include <unistd.h>

#define COORD_X_INIT -240
#define COORD_Y_INIT -240
#define COORD_X_OBJ 0
#define COORD_Y_OBJ 0
#define PI 3.141592653589793238462643383279
#define ORIENTATION_INIT PI/4

void calcul_nouvelle_position (double* x, double* y, double pas, double orientation){
	*x = *x + pas*cos(orientation);
   	*y = *y + pas*sin(orientation);
}

int main (){
	FILE* log = fopen("log.txt","a+");

	double x = COORD_X_INIT;
	double y = COORD_Y_INIT;
	double orientation = ORIENTATION_INIT;


	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD TURN -0.5\n");
	orientation += -0.5;
	fflush(stdout);
	sleep(1);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD TURN -0.5\n");
	orientation += -0.5;
	fflush(stdout);
	sleep(1);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD TURN 0.5\n");
	orientation += 0.5;
	fflush(stdout);
	sleep(1);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD TURN 0.5\n");
	orientation += 0.5;
	fflush(stdout);
	sleep(1);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD TURN 0.5\n");
	orientation += 0.5;
	fflush(stdout);
	sleep(1);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD TURN 0.5\n");
	orientation += 0.5;
	fflush(stdout);
	sleep(1);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD TURN -0.5\n");
	orientation += -0.5;
	fflush(stdout);
	sleep(1);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);
	fprintf(stdout,"CMD FORWARD 5.0\n");
	calcul_nouvelle_position(&x, &y, 5.0, orientation);
	fflush(stdout);
	sleep(1);
	fprintf(log, "x = %f, y = %f, orientation = %f\n", x, y, orientation);
	fflush(log);

	sleep(15);
	exit(0);
}